### ISSUE TITLE
Error while trying to install the package

### ISSUE THREAD

**Issue by kudak3** [tgozo19/laravel-codegen#17]
When I try to install the package  i get the following error 
```

In InitCommand.php line 919:
                                 
  Could not find a version of p  
  ackage tgozo/laravel-codegen   
  matching your minimum-stabili  
  ty (stable). Require it with   
  an explicit version constrain  
  t allowing its desired stabil  
  ity.                           
                                 

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```
This might be nothing depending on my level of expertise . For  a php newbie try out the package this throws one of their game . Maybe you should have a section on the read me  file where you explain the error and how to overcome it . But again this might be not a big deal.

**Comment by kudak3** [comment]
In case this turns out to be a bug here is how my environment looks like 
```
PHP 8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.13, Copyright (c), by Zend Technologies
```
and composer 
`Composer 2.2.6 2022-02-04 17:00:38`

**Comment by kudak3** [comment]
why trying to fight this  tried to manually add the package but I got the following 
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - Root composer.json requires tgozo/laravel-codegen ~1.0, found tgozo/laravel-codegen[v1.x-dev] but it does not match your minimum-stability.
```

**Comment by tgozo19** [comment]
Hello @kudak3. Thank you for the feedback. The issue has been resolved. It was because I hadn't released any version of the package which matched the minimum-stability in your project's `composer.json` file. May you kindly try to install again
